AWSTemplateFormatVersion: 2010-09-09
Description: This template creates security groups for VPC

Resources:
  AllowPublicSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: allow-public-ssh
      GroupDescription: Allows SSH connection over Public Internet
      VpcId: !ImportValue TestVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: allow-public-ssh

  AllowPublicHTTP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: allow-public-http
      GroupDescription: Allows HTTP connection over Public Internet
      VpcId: !ImportValue TestVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: allow-public-http

Outputs:
  AllowPublicSSH:
    Description: Security Group ID for allow-public-ssh
    Value: !Ref AllowPublicSSH
    Export:
      Name: AllowPublicSSH

  AllowPublicHTTP:
    Description: Security Group ID for allow-public-http
    Value: !Ref AllowPublicHTTP
    Export:
      Name: AllowPublicHTTP
